version: "3.3"
services:
  php-apache:
    build:
      context: './php-apache/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    depends_on:
      - mariadb
    networks:
      - backend
    ports:
      - "80:80"
    volumes:
      - ${PROJECT_PATH}:/app/
    environment:
      - APACHE_RUN_USER=${APACHE_RUN_USER}
      - APACHE_RUN_GROUP=${APACHE_RUN_GROUP}
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    container_name: "${APACHE_NAME}"
    env_file:
        - .env

  mariadb:
    image: mariadb:${MARIADB_VERSION:-latest}
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - backend
    env_file:
        - .env
    #environment:
    #  - MYSQL_ROOT_PASSWORD=whatever
    #  - MYSQL_DATABASE="${DB_NAME}"
    #  - MYSQL_USER="${DB_USERNAME}"
    #  - MYSQL_PASSWORD="${DB_PASSWORD}"
    #  - MYSQL_NAME="${DB_NAME}"
    container_name: "${MARIADB_NAME}"

    #adminer:
    #  image: adminer
    #  ports:
    #    - 8080:8080
    #  networks:
    #    - backend
    #  restart: always
    #  container_name: "${ADMINER_NAME}"
    
networks:
  backend:
  frontend:
